process.env.FIRESTORE_EMULATOR_HOST = process.env.FIRESTORE_EMULATOR_HOST ?? "127.0.0.1:8080";
import assert from "node:assert/strict";
import admin from "firebase-admin";
admin.initializeApp({ projectId: "taylor-parts" });
const db = admin.firestore();
const { updateStockLocation, createTransferOrder, completeTransferOrder } = await import("../lib/warehouseService.js");
const id = `${Date.now()}`;
const from = `source-${id}`, to = `destination-${id}`;
await updateStockLocation(from, "P-1", "A-01", 5);
const order = await createTransferOrder({ partId: "P-1", quantity: 3, fromWarehouseId: from, toWarehouseId: to, fromBinCode: "A-01", toBinCode: "B-02" });
await completeTransferOrder(order.id);
const source = await db.collection("stock_locations").doc(`${from}__P-1__A-01`).get();
const destination = await db.collection("stock_locations").doc(`${to}__P-1__B-02`).get();
assert.equal(source.data().quantity, 2);
assert.equal(destination.data().quantity, 3);
assert.equal((await db.collection("stock_locations").where("binCode", "==", "TRANSFER").get()).empty, true);
await completeTransferOrder(order.id);
assert.equal((await db.collection("stock_locations").doc(`${to}__P-1__B-02`).get()).data().quantity, 3);
console.log("warehouse transfer bin integrity passed");
