import assert from "node:assert/strict";
import { AUTHORITATIVE_AUTHORITIES, REJECTED_COMPATIBILITY_TYPES, analyzeCompatibilityEvidence, buildCompatibilityId, detectCompatibilityCollisions, sha256Hex, validateApplicability, validateCompatibility, validateCompatibilitySource } from "../src/domain/equipmentCompatibility.js";
let passed=0; const ok=(n,f)=>{f();passed++;console.log(`PASS -- ${n}`);};
const EMID="TAYLOR--C713", EMID2="TAYLOR--C825", PART="TST-1001";
const scheme={schemeId:"TAYLOR-ALPHA",manufacturerId:"Taylor",normalizerVersion:1,tokenPattern:"^[A-Z0-9-]+$",ordering:"LEXICOGRAPHIC"};
const schemes={"TAYLOR-ALPHA":scheme};
const ALL_SERIALS={kind:"ALL_SERIALS",serialScheme:null,serialRangeStart:null,serialRangeEnd:null,modelRevision:null};
const base=(over={})=>({equipmentModelId:EMID,partId:PART,compatibilityType:"DIRECT_FIT",assembly:null,installationPosition:null,quantityRequired:1,applicability:{...ALL_SERIALS},effectiveFrom:null,effectiveTo:null,sourceSummary:null,confidenceLevel:"HIGH",verificationStatus:"VERIFIED",notes:null,version:1,...over});
const vc=(over,opts={serialSchemes:schemes})=>validateCompatibility(base(over),opts);
// A real compatibilityId for evidence fixtures.
const CID=validateCompatibility(base(),{serialSchemes:schemes}).value.compatibilityId;
const FP="a".repeat(64);
const src=(over={})=>({compatibilityId:CID,authorityType:"MANUFACTURER",sourceReference:"Service Manual 12",sourceVersion:null,observedClaim:"SUPPORTS",contentFingerprint:FP,notes:null,...over});

// ---- deterministic opaque IDs (§5 / D-COMPAT-2) ----
ok("sha256 known-answer",()=>{assert.equal(sha256Hex(""),"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");assert.equal(sha256Hex("abc"),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");});
ok("compatibility id is deterministic + opaque",()=>{const a=vc(),b=vc();assert.equal(a.valid,true);assert.match(a.value.compatibilityId,/^cmp_[0-9a-f]{64}$/);assert.equal(a.value.compatibilityId,b.value.compatibilityId);});
ok("uniquenessKey is the versioned unhashed tuple",()=>{const k=vc().value.uniquenessKey;const t=JSON.parse(k);assert.equal(t[0],1);assert.equal(t[1],EMID);assert.equal(t[2],PART);assert.equal(buildCompatibilityId(k),vc().value.compatibilityId);});
ok("identity tuple determines id; non-identity fields do not",()=>{const idOf=(o)=>vc(o).value.compatibilityId;assert.equal(idOf({confidenceLevel:"LOW",notes:"x",quantityRequired:9,sourceSummary:"s"}),idOf({}));assert.notEqual(idOf({compatibilityType:"CONSUMABLE"}),idOf({}));assert.notEqual(idOf({assembly:"Motor"}),idOf({}));assert.notEqual(idOf({partId:"TST-2002"}),idOf({}));assert.notEqual(idOf({equipmentModelId:EMID2}),idOf({}));});
ok("distinct applicability → distinct id",()=>{assert.notEqual(vc({applicability:{kind:"MODEL_REVISION",serialScheme:null,serialRangeStart:null,serialRangeEnd:null,modelRevision:"REV-A"}}).value.compatibilityId,vc().value.compatibilityId);});

// ---- relationship contract (§4.2), strict unknown-field rejection ----
ok("valid relationship",()=>{const r=vc();assert.equal(r.valid,true);assert.match(r.value.compatibilityId,/^cmp_/);assert.equal(r.value.applicability.kind,"ALL_SERIALS");});
ok("unknown field rejected",()=>assert.equal(vc({foo:1}).reason,"unknown_field"));
ok("noncanonical equipment model id rejected",()=>{assert.equal(vc({equipmentModelId:"taylor--c713"}).reason,"equipment_model_id_invalid");assert.equal(vc({equipmentModelId:"A"}).reason,"equipment_model_id_invalid");});
ok("invalid part id rejected (preserve real IDs, reject garbage)",()=>{assert.equal(vc({partId:"bad id!"}).reason,"part_id_invalid");assert.equal(vc({partId:""}).reason,"part_id_invalid");assert.equal(vc({partId:"TST-1001"}).valid,true);});
ok("rejected compatibility types denied (supersession/kit/serial/universal/review)",()=>{for(const t of REJECTED_COMPATIBILITY_TYPES) assert.equal(vc({compatibilityType:t}).reason,"compatibility_type_invalid",`expected reject: ${t}`);assert.equal(vc({compatibilityType:"WHATEVER"}).reason,"compatibility_type_invalid");});
ok("quantity must be positive integer or null",()=>{assert.equal(vc({quantityRequired:0}).reason,"quantity_required_invalid");assert.equal(vc({quantityRequired:1.5}).reason,"quantity_required_invalid");assert.equal(vc({quantityRequired:null}).valid,true);});
ok("version must be positive integer",()=>{assert.equal(vc({version:0}).reason,"version_invalid");assert.equal(vc({version:"1"}).reason,"version_invalid");});
ok("effective range validated (iso + order)",()=>{assert.equal(vc({effectiveFrom:"2026-13-01"}).reason,"effective_from_invalid");assert.equal(vc({effectiveFrom:"2026-02-30"}).reason,"effective_from_invalid");assert.equal(vc({effectiveFrom:"2026-05-10",effectiveTo:"2026-05-01"}).reason,"effective_range_reversed");assert.equal(vc({effectiveFrom:"2026-05-01",effectiveTo:"2026-05-10"}).valid,true);});
ok("UNRESOLVED applicability cannot be published as VERIFIED",()=>{const unresolved={kind:"UNRESOLVED",serialScheme:null,serialRangeStart:null,serialRangeEnd:null,modelRevision:null};assert.equal(vc({applicability:unresolved,verificationStatus:"VERIFIED"}).reason,"unresolved_cannot_be_verified");assert.equal(vc({applicability:unresolved,verificationStatus:"IN_REVIEW"}).valid,true);});

// ---- applicability contract (§4.2, §5) ----
ok("applicability: unknown field + not object + bad kind",()=>{assert.equal(validateApplicability(null,schemes).reason,"not_object");assert.equal(validateApplicability({...ALL_SERIALS,extra:1},schemes).reason,"unknown_field");assert.equal(validateApplicability({...ALL_SERIALS,kind:"NOPE"},schemes).reason,"kind_invalid");});
ok("ALL_SERIALS requires all serial/revision fields null",()=>{assert.equal(validateApplicability({...ALL_SERIALS},schemes).valid,true);assert.equal(validateApplicability({...ALL_SERIALS,serialRangeStart:"A1"},schemes).reason,"fields_must_be_null");});
ok("MODEL_REVISION requires revision, null serials",()=>{assert.equal(validateApplicability({kind:"MODEL_REVISION",serialScheme:null,serialRangeStart:null,serialRangeEnd:null,modelRevision:"rev-a"},schemes).value.modelRevision,"REV-A");assert.equal(validateApplicability({kind:"MODEL_REVISION",serialScheme:null,serialRangeStart:"A1",serialRangeEnd:null,modelRevision:"REV-A"},schemes).reason,"serial_fields_must_be_null");assert.equal(validateApplicability({kind:"MODEL_REVISION",serialScheme:null,serialRangeStart:null,serialRangeEnd:null,modelRevision:"  "},schemes).reason,"model_revision_invalid");});
ok("SERIAL_RANGE resolves scheme + validates bounds; never lexical-only",()=>{const r=validateApplicability({kind:"SERIAL_RANGE",serialScheme:"taylor-alpha",serialRangeStart:" a100 ",serialRangeEnd:"A200",modelRevision:null},schemes);assert.equal(r.valid,true);assert.equal(r.value.serialRangeStart,"A100");assert.equal(r.value.serialScheme,"TAYLOR-ALPHA");});
ok("SERIAL_RANGE open bound allowed; both-null is not a range",()=>{assert.equal(validateApplicability({kind:"SERIAL_RANGE",serialScheme:"TAYLOR-ALPHA",serialRangeStart:"A100",serialRangeEnd:null,modelRevision:null},schemes).valid,true);assert.equal(validateApplicability({kind:"SERIAL_RANGE",serialScheme:"TAYLOR-ALPHA",serialRangeStart:null,serialRangeEnd:null,modelRevision:null},schemes).reason,"serial_range_empty_range");});
ok("SERIAL_RANGE unresolved/invalid scheme fails closed",()=>{assert.equal(validateApplicability({kind:"SERIAL_RANGE",serialScheme:"MISSING",serialRangeStart:"A1",serialRangeEnd:null,modelRevision:null},schemes).reason,"serial_scheme_unresolved");assert.equal(validateApplicability({kind:"SERIAL_RANGE",serialScheme:"",serialRangeStart:"A1",serialRangeEnd:null,modelRevision:null},schemes).reason,"serial_scheme_required");assert.equal(validateApplicability({kind:"SERIAL_RANGE",serialScheme:"TAYLOR-ALPHA",serialRangeStart:"A1",serialRangeEnd:null,modelRevision:"REV-A"},schemes).reason,"model_revision_must_be_null");});
ok("serial ordering is code-unit not numeric; serials stay strings",()=>{assert.equal(validateApplicability({kind:"SERIAL_RANGE",serialScheme:"TAYLOR-ALPHA",serialRangeStart:"A9",serialRangeEnd:"A10",modelRevision:null},schemes).reason,"serial_range_range_reversed");const r=validateApplicability({kind:"SERIAL_RANGE",serialScheme:"TAYLOR-ALPHA",serialRangeStart:"A10",serialRangeEnd:"A9",modelRevision:null},schemes);assert.equal(r.valid,true);assert.equal(typeof r.value.serialRangeStart,"string");});

// ---- evidence contract (§4.3) ----
ok("valid evidence + deterministic sourceId",()=>{const r=validateCompatibilitySource(src());assert.equal(r.valid,true);assert.match(r.value.sourceId,/^src_[0-9a-f]{64}$/);assert.equal(r.value.authorityType,"MANUFACTURER");});
ok("evidence strict rejects: field/id/authority/claim/fingerprint",()=>{assert.equal(validateCompatibilitySource(src({extra:1})).reason,"unknown_field");assert.equal(validateCompatibilitySource(src({compatibilityId:"cmp_xyz"})).reason,"compatibility_id_invalid");assert.equal(validateCompatibilitySource(src({authorityType:"WIKI"})).reason,"authority_type_invalid");assert.equal(validateCompatibilitySource(src({observedClaim:"MAYBE"})).reason,"observed_claim_invalid");assert.equal(validateCompatibilitySource(src({contentFingerprint:"short"})).reason,"content_fingerprint_invalid");assert.equal(validateCompatibilitySource(src({sourceReference:"   "})).reason,"source_reference_invalid");});

// ---- source precedence + conflict (§4.3, §5 / D-COMPAT-4) ----
ok("manufacturer outranks reseller in precedence ordering",()=>{const r=analyzeCompatibilityEvidence([src({authorityType:"RESELLER",contentFingerprint:"b".repeat(64)}),src({authorityType:"MANUFACTURER"})]);assert.equal(r.strongestSupport,"MANUFACTURER");assert.equal(r.supporting[0].authorityType,"MANUFACTURER");assert.equal(r.supporting[1].authorityType,"RESELLER");});
ok("authoritative support is verifiable; reseller/work-order-only is evidence-only",()=>{assert.equal(analyzeCompatibilityEvidence([src({authorityType:"MANUFACTURER"})]).recommendedStatus,"SUPPORTS_AUTHORITATIVE");assert.equal(analyzeCompatibilityEvidence([src({authorityType:"RESELLER"})]).recommendedStatus,"SUPPORTS_EVIDENCE_ONLY");assert.equal(analyzeCompatibilityEvidence([src({authorityType:"WORK_ORDER_OBSERVATION"})]).authoritativeSupport,false);});
ok("contradiction → visible CONFLICT; precedence never auto-verifies",()=>{const r=analyzeCompatibilityEvidence([src({authorityType:"MANUFACTURER"}),src({authorityType:"RESELLER",observedClaim:"CONTRADICTS",contentFingerprint:"c".repeat(64)})]);assert.equal(r.hasConflict,true);assert.equal(r.recommendedStatus,"CONFLICT");assert.equal(r.supporting.length,1);assert.equal(r.contradicting.length,1);assert.equal(r.strongestSupport,"MANUFACTURER");assert.equal(r.strongestContradiction,"RESELLER");});
ok("inconclusive-only and no-evidence",()=>{assert.equal(analyzeCompatibilityEvidence([src({observedClaim:"INCONCLUSIVE"})]).recommendedStatus,"INCONCLUSIVE");assert.equal(analyzeCompatibilityEvidence([]).recommendedStatus,"NO_EVIDENCE");});
ok("malformed evidence surfaced; cannot hide a real conflict",()=>{const r=analyzeCompatibilityEvidence([src({authorityType:"MANUFACTURER"}),null,src({authorityType:"RESELLER",observedClaim:"CONTRADICTS",contentFingerprint:"c".repeat(64)})]);assert.equal(r.hasConflict,true);assert.deepEqual(r.invalid,[{index:1,reason:"not_object"}]);});
ok("evidence ordering deterministic within equal rank (code-unit sourceId)",()=>{const a=src({authorityType:"MANUFACTURER",sourceReference:"AAA"}),b=src({authorityType:"MANUFACTURER",sourceReference:"BBB"});const r=analyzeCompatibilityEvidence([a,b]);const ids=r.supporting.map(e=>e.sourceId);assert.deepEqual([...ids].sort(),ids);});

// ---- identity collision refusal (§5) ----
ok("equivalent duplicate is idempotent, not a collision",()=>{const rec=base();const r=detectCompatibilityCollisions([rec,structuredClone(rec)],{serialSchemes:schemes});assert.equal(r.collisions.length,0);assert.equal(r.duplicates.length,1);assert.equal(r.duplicates[0].indexes.length,2);});
ok("same id + non-equivalent content → collision refused",()=>{const r=detectCompatibilityCollisions([base(),base({confidenceLevel:"LOW"})],{serialSchemes:schemes});assert.equal(r.collisions.length,1);assert.deepEqual(r.collisions[0].indexes,[0,1]);assert.equal(r.duplicates.length,0);});
ok("distinct tuples → neither collision nor duplicate",()=>{const r=detectCompatibilityCollisions([base(),base({partId:"TST-2002"})],{serialSchemes:schemes});assert.equal(r.collisions.length,0);assert.equal(r.duplicates.length,0);});
ok("collision analysis is fail-visible + non-array fail-closed",()=>{const r=detectCompatibilityCollisions([base(),{bogus:true}],{serialSchemes:schemes});assert.equal(r.invalid.length,1);assert.equal(r.invalid[0].reason,"unknown_field");assert.equal(detectCompatibilityCollisions("x").invalid[0].reason,"not_array");});

// ---- guardrails ----
ok("AUTHORITATIVE set excludes reseller/work-order/other",()=>{for(const a of ["RESELLER","WORK_ORDER_OBSERVATION","OTHER"]) assert.equal(AUTHORITATIVE_AUTHORITIES.includes(a),false);});
ok("uniquenessKey stable under equivalent normalization of assembly",()=>{assert.equal(vc({assembly:"  Main  Motor "}).value.uniquenessKey,vc({assembly:"Main Motor"}).value.uniquenessKey);});
console.log(`\n${passed} passed`);
