import assert from "node:assert/strict";
import * as mod from "../src/domain/equipmentCompatibilityImport.js";
import { dryRunEquipmentCompatibilityImport, parseCsv, scanSensitive, recordFingerprint, validateLimits, EXISTING_COMPARISON_UNAVAILABLE as UNAVAIL, IMPORT_PACKAGES, DEFAULT_LIMITS, LIMIT_MAXIMA } from "../src/domain/equipmentCompatibilityImport.js";
import { validateEquipmentModel } from "../src/domain/equipmentModel.js";
import { validateCompatibility, validateCompatibilitySource } from "../src/domain/equipmentCompatibility.js";
let passed=0; const ok=(n,f)=>{f();passed++;console.log(`PASS -- ${n}`);};

const scheme={schemeId:"TAYLOR-ALPHA",manufacturerId:"Taylor",normalizerVersion:1,tokenPattern:"^[A-Z0-9-]+$",ordering:"LEXICOGRAPHIC"};
const schemes={"TAYLOR-ALPHA":scheme};
const CID="cmp_3d758a636765061e05842659c64bed910955c47e047851dc693d4aba19d4b252";
const FP="a".repeat(64);
const H=(pkg)=>IMPORT_PACKAGES[pkg].join(",");
const csv=(pkg,...rows)=>[H(pkg),...rows].join("\n");
const MODEL_OK="TAYLOR--C713,Taylor,Taylor,C713,Taylor C713,,,,ACTIVE,manufacturer,1";
const MODEL_DIFF="TAYLOR--C713,Taylor,Taylor,C713,DIFFERENT NAME,,,,ACTIVE,manufacturer,1";
const ALIAS_OK="SOURCE_MODEL,Taylor,C-713,TAYLOR--C713";
const COMPAT_OK="TAYLOR--C713,TST-1001,DIRECT_FIT,,,1,ALL_SERIALS,,,,,,,,HIGH,VERIFIED,,1";
const SRC_OK=`${CID},MANUFACTURER,Service Manual 12,,SUPPORTS,${FP},2026-07-27T07:06:24Z,admin-uid-1,`;

// Existing-authority fingerprints built with the SAME validators the import uses.
const modelObj=(o={})=>({equipmentModelId:"TAYLOR--C713",manufacturerId:"Taylor",manufacturerName:"Taylor",modelNumber:"C713",displayName:"Taylor C713",family:null,subtype:null,revision:null,status:"ACTIVE",sourceAuthority:"manufacturer",version:1,...o});
const modelFp=(o={})=>recordFingerprint(validateEquipmentModel(modelObj(o)).value);
const FP_C713=modelFp();
const FP_C825=modelFp({equipmentModelId:"TAYLOR--C825",modelNumber:"C825",displayName:"Taylor C825"});
const FP_COMPAT=recordFingerprint(validateCompatibility({equipmentModelId:"TAYLOR--C713",partId:"TST-1001",compatibilityType:"DIRECT_FIT",assembly:null,installationPosition:null,quantityRequired:1,applicability:{kind:"ALL_SERIALS",serialScheme:null,serialRangeStart:null,serialRangeEnd:null,modelRevision:null},effectiveFrom:null,effectiveTo:null,sourceSummary:null,confidenceLevel:"HIGH",verificationStatus:"VERIFIED",notes:null,version:1},{serialSchemes:schemes}).value);
const SRC_VALUE=validateCompatibilitySource({compatibilityId:CID,authorityType:"MANUFACTURER",sourceReference:"Service Manual 12",sourceVersion:null,observedClaim:"SUPPORTS",contentFingerprint:FP,capturedAt:"2026-07-27T07:06:24Z",capturedBy:"admin-uid-1",notes:null}).value;
const SID=SRC_VALUE.sourceId, FP_SRC=recordFingerprint(SRC_VALUE);

const SNAP={partIds:["TST-1001","TST-2002"],serialSchemes:schemes,existingEquipmentModels:{"TAYLOR--C713":FP_C713,"TAYLOR--C825":FP_C825},existingCompatibility:{[CID]:FP_COMPAT},existingSources:{},existingModelAliases:[]};
const run=(packages,snapshots=SNAP,limits={})=>dryRunEquipmentCompatibilityImport({packages,snapshots,limits});

// ---- module surface: dry-run only, no apply/write path ----
ok("no apply/execute/write export exists (dry-run only)",()=>{for(const k of Object.keys(mod)) assert.ok(!/apply|execute|commit|write|persist/i.test(k),`unexpected export: ${k}`);});
ok("report is always dry-run and non-applyable",()=>{const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)});assert.equal(r.dryRun,true);assert.equal(r.applyable,false);});

// ---- CSV parsing: bounds, headers, line endings, decoded-char sanity ----
ok("valid parse yields records",()=>{const p=parseCsv(csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK),IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES);assert.equal(p.records.length,1);assert.equal(p.records[0].values.equipmentModelId,"TAYLOR--C713");});
ok("unknown/missing/duplicate header rejected",()=>{assert.equal(parseCsv("aliasType,manufacturerId,rawValue,equipmentModelId,extra\nx",IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"header_mismatch");assert.equal(parseCsv("aliasType,manufacturerId,rawValue",IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"header_mismatch");assert.equal(parseCsv("aliasType,aliasType,rawValue,equipmentModelId",IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"duplicate_header");});
ok("BOM / decoded replacement char / control chars rejected",()=>{assert.equal(parseCsv("﻿"+H("EQUIPMENT_MODEL_ALIASES"),IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"bom_not_allowed");assert.equal(parseCsv(H("EQUIPMENT_MODEL_ALIASES")+"\n�",IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"decoded_replacement_char");assert.equal(parseCsv(H("EQUIPMENT_MODEL_ALIASES")+"\n\x07",IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"control_characters");});
ok("CR-only line ending rejected; CRLF normalized",()=>{assert.equal(parseCsv(H("EQUIPMENT_MODEL_ALIASES")+"\rrow",IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"invalid_line_ending");const p=parseCsv(csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK).replace(/\n/g,"\r\n"),IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES);assert.equal(p.records.length,1);});
ok("column-count mismatch + field-too-long are row errors",()=>{const p=parseCsv(csv("EQUIPMENT_MODEL_ALIASES","SOURCE_MODEL,Taylor,C-713"),IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES);assert.equal(p.rowErrors[0].code,"column_count_mismatch");const q=parseCsv(csv("EQUIPMENT_MODEL_ALIASES",`SOURCE_MODEL,Taylor,${"C".repeat(40)},TAYLOR--C713`),IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES,{...DEFAULT_LIMITS,maxFieldChars:20});assert.equal(q.rowErrors[0].code,"field_too_long");});
ok("quoted fields keep embedded commas; unbalanced quote is an error",()=>{const p=parseCsv(csv("EQUIPMENT_PART_COMPATIBILITY",`TAYLOR--C713,TST-1001,DIRECT_FIT,"Main, Motor",,1,ALL_SERIALS,,,,,,,,HIGH,VERIFIED,,1`),IMPORT_PACKAGES.EQUIPMENT_PART_COMPATIBILITY);assert.equal(p.records[0].values.assembly,"Main, Motor");assert.equal(parseCsv(csv("EQUIPMENT_MODEL_ALIASES",'SOURCE_MODEL,Taylor,"C-713,TAYLOR--C713'),IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).rowErrors[0].code,"unbalanced_quote");});

// ---- per-row validation surfaced with sanitized line + code ----
ok("invalid rows surfaced with line + code (no raw values)",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER","TAYLOR--C713,Taylor,Taylor,C713,Taylor C713,,,,BOGUS,manufacturer,1")});const e=r.errors.find(x=>x.package==="EQUIPMENT_MASTER");assert.equal(e.line,2);assert.equal(e.code,"status_invalid");assert.equal(e.field,null);});
ok("noncanonical/invented model id in master is rejected, not coerced",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER","taylor--c713,Taylor,Taylor,C713,Taylor C713,,,,ACTIVE,manufacturer,1")});assert.ok(r.errors.some(e=>e.code==="id_invalid"));});

// ---- reference resolution against explicit snapshots ----
ok("unresolved partId and equipmentModelId are visible errors",()=>{const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY","TAYLOR--C999,TST-9999,DIRECT_FIT,,,1,ALL_SERIALS,,,,,,,,HIGH,VERIFIED,,1")});const codes=r.unresolved.map(u=>u.code).sort();assert.deepEqual(codes,["equipment_model_unresolved","part_unresolved"]);assert.equal(r.status,"BLOCKED");});
ok("in-batch master resolves compatibility model ref",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK),EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)},{...SNAP,existingEquipmentModels:{},existingCompatibility:{}});assert.equal(r.unresolved.length,0);});
ok("aliases cannot create models — unresolved when model absent",()=>{const r=run({EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES","SOURCE_MODEL,Taylor,C-999,TAYLOR--C999")});assert.ok(r.unresolved.some(u=>u.package==="EQUIPMENT_MODEL_ALIASES"&&u.code==="equipment_model_unresolved"));});
ok("unresolved source compatibilityId is visible",()=>{const other="cmp_"+"0".repeat(64);const r=run({COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",`${other},MANUFACTURER,Ref,,SUPPORTS,${FP},2026-07-27T07:06:24Z,admin-uid-1,`)});assert.ok(r.unresolved.some(u=>u.code==="compatibility_unresolved"));});

// ---- in-batch identity: duplicate vs collision ----
ok("in-batch model duplicate (idempotent) vs collision",()=>{const dup=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK,MODEL_OK)});assert.equal(dup.collisions.equipmentModels.length,0);assert.equal(dup.duplicatesIdempotent.equipmentModels,1);const col=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK,MODEL_DIFF)});assert.equal(col.collisions.equipmentModels.length,1);assert.deepEqual(col.collisions.equipmentModels[0].lines,[2,3]);assert.equal(col.status,"BLOCKED");});
ok("in-batch compatibility collision (same id, different content)",()=>{const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK,"TAYLOR--C713,TST-1001,DIRECT_FIT,,,1,ALL_SERIALS,,,,,,,,LOW,VERIFIED,,1")});assert.equal(r.collisions.compatibility.length,1);assert.equal(r.status,"BLOCKED");});

// ---- existing-authority identity (Codex round 1, item 1) ----
ok("equivalent existing record → idempotent duplicate",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK)},{...SNAP,existingEquipmentModels:{"TAYLOR--C713":FP_C713}});assert.equal(r.collisions.equipmentModels.length,0);assert.equal(r.duplicatesIdempotent.equipmentModels,1);});
ok("conflicting existing record (same id, different content) → collision",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_DIFF)},{...SNAP,existingEquipmentModels:{"TAYLOR--C713":FP_C713}});assert.equal(r.collisions.equipmentModels.length,1);assert.equal(r.collisions.equipmentModels[0].existing,true);assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});
ok("modeled unavailable sentinel fails closed (with overlap)",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK)},{...SNAP,existingEquipmentModels:{"TAYLOR--C713":UNAVAIL}});assert.equal(r.existingComparisonUnavailable.equipmentModels.length,1);assert.equal(r.existingComparisonUnavailable.equipmentModels[0].id,"TAYLOR--C713");assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});
ok("modeled unavailable sentinel blocks even with NO overlapping import",()=>{const r=run({},{...SNAP,existingEquipmentModels:{"TAYLOR--C713":UNAVAIL}});assert.equal(r.existingComparisonUnavailable.equipmentModels.length,1);assert.deepEqual(r.existingComparisonUnavailable.equipmentModels[0].lines,[]);assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});
ok("alias ownership conflict with EXISTING authority alias",()=>{const r=run({EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK)},{...SNAP,existingModelAliases:[{aliasType:"SOURCE_MODEL",manufacturerId:"Taylor",rawValue:"C-713",equipmentModelId:"TAYLOR--C825"}]});assert.equal(r.collisions.modelAliasConflicts.length,1);assert.equal(r.status,"BLOCKED");});
ok("source collision/duplicate vs EXISTING provenance",()=>{const dup=run({COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK)},{...SNAP,existingSources:{[SID]:FP_SRC}});assert.equal(dup.collisions.sources.length,0);assert.equal(dup.duplicatesIdempotent.sources,1);const col=run({COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK)},{...SNAP,existingSources:{[SID]:"9".repeat(64)}});assert.equal(col.collisions.sources.length,1);assert.equal(col.status,"BLOCKED");});
ok("overlapping existing source with unavailable sentinel fails closed",()=>{const r=run({COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK)},{...SNAP,existingSources:{[SID]:UNAVAIL}});assert.equal(r.existingComparisonUnavailable.sources.length,1);assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});

// ---- precedence + evidence conflict ----
ok("contradicting evidence → REVIEW_REQUIRED with visible conflict, staged null",()=>{const r=run({COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK,`${CID},RESELLER,Listing,,CONTRADICTS,${"c".repeat(64)},2026-07-27T07:06:24Z,admin-uid-1,`)});assert.equal(r.status,"REVIEW_REQUIRED");assert.equal(r.conflicts.length,1);assert.equal(r.conflicts[0].strongestSupport,"MANUFACTURER");assert.equal(r.conflicts[0].strongestContradiction,"RESELLER");assert.equal(r.staged,null);});
ok("in-batch source collision (changed claim, same source identity)",()=>{const r=run({COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK,`${CID},MANUFACTURER,Service Manual 12,,CONTRADICTS,${FP},2026-07-27T07:06:24Z,admin-uid-1,`)});assert.equal(r.collisions.sources.length,1);assert.equal(r.status,"BLOCKED");});

// ---- staging matrix (Codex round 1, item 3) ----
ok("staged only for READY; null for REVIEW_REQUIRED and BLOCKED",()=>{const ready=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)},{...SNAP,existingCompatibility:{}});assert.equal(ready.status,"READY");assert.ok(ready.staged&&ready.staged.compatibilityIds[0]===CID);const review=run({COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK,`${CID},RESELLER,Listing,,CONTRADICTS,${"c".repeat(64)},2026-07-27T07:06:24Z,admin-uid-1,`)});assert.equal(review.status,"REVIEW_REQUIRED");assert.equal(review.staged,null);const blocked=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER","TAYLOR--C713,Taylor,Taylor,C713,N,,,,BOGUS,manufacturer,1")});assert.equal(blocked.status,"BLOCKED");assert.equal(blocked.staged,null);});

// ---- market listings quarantine require review (Codex round 2, item 2) ----
const MKT_OK="L1,ebay,Taylor,C713,TST-1001,http://x,2026-07-27T00:00:00Z";
ok("market-listing-only input is REVIEW_REQUIRED, never READY/staged",()=>{const r=run({MARKET_LISTINGS:csv("MARKET_LISTINGS",MKT_OK)});assert.equal(r.status,"REVIEW_REQUIRED");assert.equal(r.staged,null);assert.equal(r.quarantine.marketListings,1);assert.equal(r.quarantine.authoritative,false);assert.ok(r.reviewReasons.includes("market_listings_require_review"));});
ok("market listings flip an otherwise-READY batch to REVIEW_REQUIRED",()=>{const snap={...SNAP,existingCompatibility:{}};const ready=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)},snap);assert.equal(ready.status,"READY");const withMkt=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK),MARKET_LISTINGS:csv("MARKET_LISTINGS",MKT_OK)},snap);assert.equal(withMkt.status,"REVIEW_REQUIRED");assert.equal(withMkt.staged,null);});
ok("malformed market listing → BLOCKED; sensitive market listing → BLOCKED",()=>{assert.equal(run({MARKET_LISTINGS:csv("MARKET_LISTINGS","only,three,cols")}).status,"BLOCKED");const s=run({MARKET_LISTINGS:csv("MARKET_LISTINGS","L1,ebay,Taylor,C713,TST-1001,mailto:admin@example.com,2026-07-27T00:00:00Z")});assert.equal(s.status,"BLOCKED");assert.equal(s.sensitive.clean,false);});

// ---- sensitive scanning blocks READY/staging (Codex round 1, item 2) ----
ok("one sensitive value flips an otherwise-READY batch to BLOCKED",()=>{const snap={...SNAP,existingCompatibility:{}};const okRun=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)},snap);assert.equal(okRun.status,"READY");const badRun=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY","TAYLOR--C713,TST-1001,DIRECT_FIT,,,1,ALL_SERIALS,,,,,,,,HIGH,VERIFIED,see admin@example.com,1")},snap);assert.equal(badRun.status,"BLOCKED");assert.equal(badRun.staged,null);assert.equal(badRun.sensitive.clean,false);});
ok("sensitive scan flags by line+code, never the value",()=>{const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY","TAYLOR--C713,TST-1001,DIRECT_FIT,,,1,ALL_SERIALS,,,,,,,,HIGH,VERIFIED,contact admin@example.com bearer sk_live_ABC,1")});const codes=r.sensitive.findings.map(f=>f.code);assert.ok(codes.includes("email")&&codes.includes("credential_keyword"));const blob=JSON.stringify(r);assert.ok(!blob.includes("admin@example.com")&&!blob.includes("sk_live_ABC"));});
ok("report never reproduces raw row values (notes/serials)",()=>{const note="ULTRASECRETNOTE",serial="ZZ-SECRET-9999";const row=`TAYLOR--C713,TST-1001,DIRECT_FIT,,,1,SERIAL_RANGE,TAYLOR-ALPHA,${serial},,,,,,HIGH,IN_REVIEW,${note},1`;const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",row)},{...SNAP,existingCompatibility:{}});const blob=JSON.stringify(r);assert.ok(!blob.includes(note)&&!blob.includes(serial));});
ok("standalone scanSensitive returns line+code only",()=>{const f=scanSensitive("ok line\nsecret=hunter2 here","P");assert.equal(f.length,1);assert.deepEqual(f[0],{package:"P",line:2,code:"credential_keyword"});});

// ---- strict limits validation, fail closed (Codex round 1, item 4) ----
ok("validateLimits accepts defaults and clean overrides",()=>{assert.deepEqual(validateLimits(undefined).limits,DEFAULT_LIMITS);assert.equal(validateLimits({maxErrorRefs:50}).ok,true);assert.equal(validateLimits({maxRows:5000,maxErrorRefs:100}).ok,true);});
ok("validateLimits rejects malformed values fail-closed",()=>{for(const [k,v,code] of [["maxRows",-1,"limit_maxRows_invalid"],["maxRows",0,"limit_maxRows_invalid"],["maxRows",1.5,"limit_maxRows_invalid"],["maxRows","5","limit_maxRows_invalid"],["maxRows",NaN,"limit_maxRows_invalid"],["maxRows",Infinity,"limit_maxRows_invalid"]]){const r=validateLimits({[k]:v});assert.equal(r.ok,false);assert.equal(r.code,code);}assert.equal(validateLimits({nope:1}).code,"unknown_limit_key");assert.equal(validateLimits({maxRows:LIMIT_MAXIMA.maxRows+1}).code,"limit_maxRows_exceeds_maximum");assert.equal(validateLimits({maxErrorRefs:9999,maxRows:100}).code,"limit_maxErrorRefs_exceeds_rows");assert.equal(validateLimits("x").code,"limits_not_object");});
ok("dry-run fails closed on invalid limits with sanitized configError",()=>{const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)},SNAP,{maxRows:-1});assert.equal(r.status,"BLOCKED");assert.equal(r.configError,"limit_maxRows_invalid");assert.equal(r.staged,null);assert.deepEqual(r.errors,[]);});

// ---- no partial apply / zero-write / determinism ----
ok("no partial apply: any blocking error empties the staged plan",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK),EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK,"TAYLOR--C713,TST-9999,DIRECT_FIT,,,1,ALL_SERIALS,,,,,,,,HIGH,VERIFIED,,1")},{...SNAP,existingEquipmentModels:{},existingCompatibility:{}});assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});
ok("clean batch stages opaque ids only",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK),EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK),EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK),COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK)},{...SNAP,existingEquipmentModels:{},existingCompatibility:{}});assert.equal(r.status,"READY");assert.deepEqual(r.staged.equipmentModelIds,["TAYLOR--C713"]);assert.deepEqual(r.staged.compatibilityIds,[CID]);assert.match(r.staged.sourceIds[0],/^src_[0-9a-f]{64}$/);});
ok("inputs are read-only (not mutated by dry run)",()=>{const packages=Object.freeze({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)});const before=JSON.stringify(SNAP);run(packages);assert.equal(JSON.stringify(SNAP),before);});
ok("deterministic replay: same input → deep-equal report",()=>{const packages={EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK,"TAYLOR--C825,Taylor,Taylor,C825,Taylor C825,,,,ACTIVE,manufacturer,1"),EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK),COMPATIBILITY_SOURCES:csv("COMPATIBILITY_SOURCES",SRC_OK)};const a=run(packages),b=run(packages);assert.deepEqual(a,b);});
ok("output ordering is deterministic (sorted errors)",()=>{const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER","TAYLOR--C713,Taylor,Taylor,C713,N,,,,BOGUS,manufacturer,1","taylor--c825,Taylor,Taylor,C825,N,,,,ACTIVE,manufacturer,1")});const lines=r.errors.map(e=>e.line);assert.deepEqual([...lines].sort((x,y)=>x-y),lines);});
ok("error refs are bounded with truncation count",()=>{const rows=Array.from({length:6},()=> "TAYLOR--C713,TST-1001,BADTYPE,,,1,ALL_SERIALS,,,,,,,,HIGH,VERIFIED,,1");const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",...rows)},SNAP,{maxErrorRefs:3});assert.equal(r.errors.length,3);assert.equal(r.truncated.errors,3);});

// ---- malformed existing aliases must block (Codex round 2, item 1) ----
ok("malformed existing alias is retained (invalid) and blocks; raw value never surfaced",()=>{const r=run({EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK)},{...SNAP,existingModelAliases:[null,{aliasType:"BOGUS",manufacturerId:"Taylor",rawValue:"SECRETALIAS",equipmentModelId:"TAYLOR--C713"}]});assert.ok(r.invalidAliases.length>=1);assert.ok(r.invalidAliases.every(x=>x.source==="existing"));assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);assert.ok(!JSON.stringify(r).includes("SECRETALIAS")&&!JSON.stringify(r).includes("BOGUS"));});
ok("malformed existing alias cannot hide a genuine ownership conflict",()=>{const r=run({EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK)},{...SNAP,existingModelAliases:[{aliasType:"SOURCE_MODEL",manufacturerId:"Taylor",rawValue:"C-713",equipmentModelId:"TAYLOR--C825"},null]});assert.equal(r.collisions.modelAliasConflicts.length,1);assert.ok(r.invalidAliases.length>=1);assert.equal(r.status,"BLOCKED");});
ok("in-batch alias line ref distinguished from existing-snapshot index",()=>{const r=run({EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK)},{...SNAP,existingModelAliases:[null]});const e=r.invalidAliases[0];assert.equal(e.source,"existing");assert.equal(e.ref,0);assert.equal(e.reason,"not_object");});
ok("non-array existingModelAliases fails closed",()=>{const r=run({EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES",ALIAS_OK)},{...SNAP,existingModelAliases:"nope"});assert.equal(r.configError,"snapshot_existingModelAliases_invalid");assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});

// ---- C0/DEL/C1 control rejection (Codex round 2, item 3) ----
ok("C0 / DEL / C1 controls rejected; normal Unicode accepted",()=>{for(const cc of ["\x00","\x7F","\x80","\x85","\x9F"]) assert.equal(parseCsv(H("EQUIPMENT_MODEL_ALIASES")+"\n"+cc,IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES).headerError,"control_characters",`code ${cc.charCodeAt(0)}`);const good=parseCsv(csv("EQUIPMENT_MODEL_ALIASES","SOURCE_MODEL,Taylör,C-713é,TAYLOR--C713"),IMPORT_PACKAGES.EQUIPMENT_MODEL_ALIASES);assert.equal(good.records.length,1);});

// ---- every report collection bounded; status from complete collection (Codex round 2, item 4) ----
ok("top-level collections bounded; truncation never changes status",()=>{const rows=["TAYLOR--C1,Taylor,Taylor,C1,N,,,,ACTIVE,manufacturer,1","TAYLOR--C2,Taylor,Taylor,C2,N,,,,ACTIVE,manufacturer,1","TAYLOR--C3,Taylor,Taylor,C3,N,,,,ACTIVE,manufacturer,1"];const existing={"TAYLOR--C1":UNAVAIL,"TAYLOR--C2":UNAVAIL,"TAYLOR--C3":UNAVAIL};const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",...rows)},{...SNAP,existingEquipmentModels:existing},{maxErrorRefs:2});assert.equal(r.existingComparisonUnavailable.equipmentModels.length,2);assert.equal(r.truncated.unavailableEquipmentModels,1);assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});
ok("NESTED collision lines are bounded with counts; status from complete data",()=>{const rows=Array.from({length:4},(_,i)=>`TAYLOR--C1,Taylor,Taylor,C1,Name${i},,,,ACTIVE,manufacturer,1`);const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",...rows)},{...SNAP,existingEquipmentModels:{}},{maxErrorRefs:2});assert.equal(r.collisions.equipmentModels.length,1);const e=r.collisions.equipmentModels[0];assert.equal(e.lines.length,2);assert.equal(e.lineCount,4);assert.equal(e.linesTruncated,2);assert.deepEqual(e.lines,[2,3]);assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});
ok("NESTED alias owner list is bounded with counts",()=>{const keys=["TAYLOR--C1","TAYLOR--C2","TAYLOR--C3","TAYLOR--C4"];const existingEquipmentModels=Object.fromEntries(keys.map(k=>[k,FP_C713]));const aliasRows=keys.map(k=>`SOURCE_MODEL,Taylor,C-713,${k}`);const r=run({EQUIPMENT_MODEL_ALIASES:csv("EQUIPMENT_MODEL_ALIASES",...aliasRows)},{...SNAP,existingEquipmentModels},{maxErrorRefs:2});assert.equal(r.collisions.modelAliasConflicts.length,1);const c=r.collisions.modelAliasConflicts[0];assert.equal(c.equipmentModelIds.length,2);assert.equal(c.ownerCount,4);assert.equal(c.ownersTruncated,2);assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});

// ---- existing-fingerprint format validation (Codex round 2, item 5) ----
ok("EVERY malformed fingerprint value fails closed as configError (never ignored/collision)",()=>{for(const bad of ["ABC","",FP_C713.toUpperCase(),"xyz",123,null,[],{},["a"]]){const r=run({EQUIPMENT_MASTER:csv("EQUIPMENT_MASTER",MODEL_OK)},{...SNAP,existingEquipmentModels:{"TAYLOR--C713":bad}});assert.equal(r.configError,"snapshot_existingEquipmentModels_invalid",`bad=${String(bad)}`);assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);assert.ok(!JSON.stringify(r).includes("ABC"));}});
ok("non-overlapping malformed authority fingerprint still blocks whole batch",()=>{const r=run({EQUIPMENT_PART_COMPATIBILITY:csv("EQUIPMENT_PART_COMPATIBILITY",COMPAT_OK)},{...SNAP,existingCompatibility:{},existingSources:{["src_"+"a".repeat(64)]:"NOTHEX"}});assert.equal(r.configError,"snapshot_existingSources_invalid");assert.equal(r.status,"BLOCKED");assert.equal(r.staged,null);});
ok("malformed snapshot shape / keys fail closed; strict plain-object rejects exotic shapes",()=>{assert.equal(run({},{partIds:"x"}).configError,"snapshot_partIds_invalid");assert.equal(run({},{existingEquipmentModels:[]}).configError,"snapshot_existingEquipmentModels_invalid");assert.equal(run({},{existingEquipmentModels:{"bad key":FP_C713}}).configError,"snapshot_existingEquipmentModels_invalid");assert.equal(run({},{existingCompatibility:{"nope":FP_COMPAT}}).configError,"snapshot_existingCompatibility_invalid");assert.equal(run({},{existingSources:{"nope":FP_SRC}}).configError,"snapshot_existingSources_invalid");assert.equal(run({},{weird:1}).configError,"unknown_snapshot_key");assert.equal(run({},{serialSchemes:[]}).configError,"snapshot_serialSchemes_invalid");assert.equal(run({},{serialSchemes:new Date()}).configError,"snapshot_serialSchemes_invalid");assert.equal(dryRunEquipmentCompatibilityImport({snapshots:new Date()}).configError,"snapshots_not_object");});

console.log(`\n${passed} passed`);
