import assert from "node:assert/strict";
import { buildEquipmentModelId, detectModelAliasConflicts, normalizeEquipmentModel, normalizeIdentityText, normalizeModelAliasKey, normalizeSerialToken, validateEquipmentModel, validateSerialRange, validateSerialScheme } from "../src/domain/equipmentModel.js";
let passed=0; const ok=(n,f)=>{f();passed++;console.log(`PASS -- ${n}`);};
const scheme={schemeId:"TAYLOR.ALPHA",manufacturerId:"Taylor",normalizerVersion:1,tokenPattern:"^[A-Z0-9-]+$",ordering:"LEXICOGRAPHIC"};
ok("Unicode/space normalization",()=>assert.equal(normalizeIdentityText(" Model  Ａ "),"Model A"));
ok("deterministic model id",()=>assert.equal(buildEquipmentModelId("Taylor Company"," C713-33 "),"TAYLOR-COMPANY--C713-33"));
ok("normalization is non-mutating",()=>{const i={manufacturerId:"Taylor",modelNumber:" c713 ",family:""};const b=structuredClone(i);assert.equal(normalizeEquipmentModel(i).family,null);assert.deepEqual(i,b);});
ok("valid strict model",()=>assert.equal(validateEquipmentModel({equipmentModelId:"TAYLOR--C713",manufacturerId:"Taylor",manufacturerName:"Taylor",modelNumber:"C713",displayName:"Taylor C713",family:null,subtype:null,revision:null,status:"active",sourceAuthority:"manufacturer",version:1}).valid,true));
ok("mismatched id denied",()=>assert.equal(validateEquipmentModel({equipmentModelId:"OTHER",manufacturerId:"Taylor",manufacturerName:"Taylor",modelNumber:"C713",displayName:"Taylor C713",status:"ACTIVE",sourceAuthority:"mfr",version:1}).reason,"id_invalid"));
ok("unknown field denied",()=>assert.equal(validateEquipmentModel({manufacturerId:"Taylor",modelNumber:"C713",secret:"x"}).reason,"unknown_field"));
ok("alias identity scoped",()=>assert.equal(normalizeModelAliasKey({aliasType:"source_model",manufacturerId:"Taylor",rawValue:" c-713 "}),"SOURCE_MODEL|TAYLOR|C-713"));
ok("same-owner alias is clean",()=>assert.deepEqual(detectModelAliasConflicts([{aliasType:"SOURCE_MODEL",manufacturerId:"Taylor",rawValue:"C713",equipmentModelId:"TAYLOR--C713"},{aliasType:"source_model",manufacturerId:"taylor",rawValue:" c713 ",equipmentModelId:"TAYLOR--C713"}]),[]));
ok("cross-owner alias conflict visible",()=>assert.equal(detectModelAliasConflicts([{aliasType:"SOURCE_MODEL",manufacturerId:"Taylor",rawValue:"C713",equipmentModelId:"A"},{aliasType:"SOURCE_MODEL",manufacturerId:"Taylor",rawValue:"C713",equipmentModelId:"B"}]).length,1));
ok("serial scheme valid",()=>assert.equal(validateSerialScheme(scheme).valid,true));
ok("bad regex denied",()=>assert.equal(validateSerialScheme({...scheme,tokenPattern:"["}).valid,false));
ok("ordering must be explicit",()=>assert.equal(validateSerialScheme({...scheme,ordering:"NUMERIC"}).reason,"ordering_invalid"));
ok("alphanumeric serial preserved",()=>assert.equal(normalizeSerialToken(" ab-019 ",scheme),"AB-019"));
ok("open range valid",()=>assert.equal(validateSerialRange({start:"A100",end:null,scheme}).valid,true));
ok("reversed range denied",()=>assert.equal(validateSerialRange({start:"Z900",end:"A100",scheme}).reason,"range_reversed"));
ok("empty range denied",()=>assert.equal(validateSerialRange({start:null,end:null,scheme}).reason,"empty_range"));
console.log(`\n${passed} passed`);
