// LEGACY WORK ORDER COMPLAINT TEXT — replace a stored document id with the governed reference.
//
// ════════════════════ WHAT IS WRONG, AND WHAT IS NOT ════════════════════
//
// Six sandbox Work Orders carry, in their STORED complaint text:
//
//     Sales Order fulfillment cIk3hlPDTXH5IB3VHdLy: deliver/install ordered items
//
// That sentence was machine-generated by the old createServiceForSalesOrder, which interpolated the
// Sales Order's Firestore document id. The code is already fixed for future writes -- it emits the
// allocated SO-YYYY-###### and falls back to a reference-free sentence when no number exists. What
// remains is the text already written down, and no amount of correct code changes a stored string.
//
// This is DATA, not rendering. Masking it at the surface would be a lie told twice: the record would
// still say the wrong thing, and the detector that found it would be blinded to the next one.
//
// ════════════════════ WHY THIS IS NOT A "FIX THE TEXT" SCRIPT ════════════════════
//
// A regex that finds id-shaped strings in free text and swaps them is the most dangerous shape this
// task could take. `complaint` is a field a human being types into -- "customer says unit at
// A1B2C3D4E5F6G7H8I9J0 is leaking" is somebody's words, and a migration that rewrote it would be
// destroying a service record to satisfy a lint rule.
//
// So eligibility is proven, never inferred, and every one of these must hold:
//
//   1. The complaint matches the legacy template EXACTLY, anchored at both ends. Not "contains an
//      id" -- IS the machine sentence, character for character, with the id in the one slot the old
//      writer put it in.
//   2. The extracted id resolves to a Sales Order that actually exists.
//   3. That Sales Order carries a governed SO-YYYY-###### number.
//   4. The Work Order's OWN salesOrderId agrees with the id embedded in the text. This is the
//      corroboration that matters: it proves the string is a reference to that order rather than a
//      coincidence, using a field the old writer set separately.
//
// Any failure is a SKIP with a stated reason. Never a best-effort rewrite.
//
// ════════════════════ WHAT CHANGES ════════════════════
//
// One field, on records that pass all four proofs: `complaint`. Not status, not scheduling, not
// ownership, not timestamps, not the inventory snapshot. The sentence keeps every other word,
// including its punctuation -- only the identifier inside it becomes the one a person can read.

/** The EXACT sentence the old writer emitted. Anchored: a partial match is not a match. */
export const LEGACY_COMPLAINT_PATTERN =
  /^Sales Order fulfillment ([A-Za-z0-9]{20}): deliver\/install ordered items$/;

/** The sentence the fixed writer emits today, so the corrected text is not a third variant. */
export const correctedComplaint = (salesOrderNumber: string): string =>
  `Sales Order fulfillment ${salesOrderNumber}: deliver/install ordered items`;

export const GOVERNED_SO_NUMBER = /^SO-\d{4}-\d{6}$/;

/** A guard against an unbounded run, not an expected size. The known set is six. */
export const MAX_MIGRATED_WORK_ORDERS = 25;

export type SkipReason =
  | "NOT_LEGACY_TEMPLATE"
  | "SALES_ORDER_NOT_FOUND"
  | "NO_GOVERNED_NUMBER"
  | "LINK_DISAGREES"
  | "ALREADY_CORRECT";

export interface WorkOrderRecord {
  workOrderId: string;
  woNumber: string | null;
  complaint: unknown;
  /** The Work Order's own link, written separately by the same legacy path. */
  salesOrderId: string | null;
}

/** What the caller resolved for an embedded id, through the GOVERNED Sales Order read. */
export interface SalesOrderResolution {
  exists: boolean;
  salesOrderNumber: string | null;
}

export interface PlannedChange {
  workOrderId: string;
  woNumber: string | null;
  embeddedSalesOrderId: string;
  salesOrderNumber: string;
  before: string;
  after: string;
}

export interface SkippedRecord {
  workOrderId: string;
  woNumber: string | null;
  reason: SkipReason;
  detail: string;
}

export interface MigrationPlan {
  scanned: number;
  changes: PlannedChange[];
  skipped: SkippedRecord[];
  /** Deterministic over the ORDERED plan content. The apply run must be handed this exact value. */
  fingerprint: string;
}

/**
 * A stable fingerprint of the plan, so an apply run cannot execute a plan nobody reviewed.
 *
 * Deliberately NOT a hash import: this module is imported by both the Functions build and the
 * offline test runner, and a plain content digest keeps it dependency-free and readable in a report.
 * Its job is to detect DRIFT between review and execution, not to resist an adversary who already
 * has write access to the database.
 */
export function planFingerprint(changes: PlannedChange[]): string {
  const canonical = [...changes]
    .sort((a, b) => a.workOrderId.localeCompare(b.workOrderId))
    .map((c) => `${c.workOrderId}|${c.embeddedSalesOrderId}|${c.salesOrderNumber}|${c.before}|${c.after}`)
    .join("\n");
  let h1 = 0x811c9dc5;
  let h2 = 0x01000193;
  for (let i = 0; i < canonical.length; i++) {
    const ch = canonical.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 0x01000193) >>> 0;
    h2 = Math.imul(h2 + ch + i, 0x85ebca6b) >>> 0;
  }
  return `${changes.length}-${h1.toString(16).padStart(8, "0")}${h2.toString(16).padStart(8, "0")}`;
}

/**
 * THE PURE PLANNER. No Firestore, no clock, no writes.
 *
 * Pure on purpose: the entire eligibility argument is assertable offline, and the DRY RUN a reviewer
 * reads is produced by the SAME function the apply run uses to decide. A planner that only ran
 * against a live database could not be examined before it was trusted.
 *
 * @param records  every Work Order in the bounded scan
 * @param resolve  the embedded id -> governed Sales Order, resolved by the CALLER through the
 *                 governed read (sales_orders is Rules-closed; there is no client shortcut)
 */
export function planWorkOrderComplaintCorrection(
  records: readonly WorkOrderRecord[],
  resolve: (salesOrderId: string) => SalesOrderResolution,
): MigrationPlan {
  const changes: PlannedChange[] = [];
  const skipped: SkippedRecord[] = [];

  for (const r of records) {
    const complaint = typeof r.complaint === "string" ? r.complaint : "";
    const match = LEGACY_COMPLAINT_PATTERN.exec(complaint);
    if (!match) {
      // Silent unless it LOOKS like it should have matched. Reporting every ordinary work order as
      // "skipped" would bury the six that matter under a hundred that were never candidates.
      if (/\b[A-Za-z0-9]{20}\b/.test(complaint)) {
        skipped.push({
          workOrderId: r.workOrderId,
          woNumber: r.woNumber,
          reason: "NOT_LEGACY_TEMPLATE",
          detail: "carries an id-shaped string but is NOT the machine template — never rewritten heuristically",
        });
      }
      continue;
    }

    const embedded = match[1];
    const so = resolve(embedded);
    if (!so.exists) {
      skipped.push({ workOrderId: r.workOrderId, woNumber: r.woNumber, reason: "SALES_ORDER_NOT_FOUND",
        detail: `embedded ${embedded} resolves to no Sales Order` });
      continue;
    }
    if (typeof so.salesOrderNumber !== "string" || !GOVERNED_SO_NUMBER.test(so.salesOrderNumber)) {
      // An order with no allocated number has no governed reference to substitute. Inventing one, or
      // falling back to the reference-free sentence, would both change what the record SAYS.
      skipped.push({ workOrderId: r.workOrderId, woNumber: r.woNumber, reason: "NO_GOVERNED_NUMBER",
        detail: `Sales Order ${embedded} carries no SO-YYYY-###### reference` });
      continue;
    }
    if (r.salesOrderId !== embedded) {
      // THE CORROBORATION. Without it, the id in the text is just a string that looks like an id.
      skipped.push({ workOrderId: r.workOrderId, woNumber: r.woNumber, reason: "LINK_DISAGREES",
        detail: `work order links ${r.salesOrderId ?? "nothing"} but the text embeds ${embedded}` });
      continue;
    }

    const after = correctedComplaint(so.salesOrderNumber);
    if (after === complaint) {
      skipped.push({ workOrderId: r.workOrderId, woNumber: r.woNumber, reason: "ALREADY_CORRECT",
        detail: "already carries the governed reference" });
      continue;
    }
    changes.push({
      workOrderId: r.workOrderId,
      woNumber: r.woNumber,
      embeddedSalesOrderId: embedded,
      salesOrderNumber: so.salesOrderNumber,
      before: complaint,
      after,
    });
  }

  return { scanned: records.length, changes, skipped, fingerprint: planFingerprint(changes) };
}
