// WORKFLOW SELF-PUSH FENCE. Refuses a NEW workflow that commits repository content and pushes it
// back with the default GITHUB_TOKEN, beyond the three that already exist.
//
// ============================ THE FAILURE THIS EXISTS TO STOP ============================
//
// 7861c580 (a human commit, on the PR branch of #1929) added
// .github/workflows/crm-retire-firestore-writes-apply.yml: `permissions: contents: write`,
// `on: push` to its own feature branch, a Python rewriter of firestore.rules, and a final
// `git push origin HEAD:crm/nonprod-retire-firestore-writes` as github-actions[bot].
//
// It ran, it rewrote both firestore.rules copies, and it pushed c9399b52 to the PR branch.
//
// GitHub does not create workflow runs for events generated by the default GITHUB_TOKEN. So the
// `pull_request: synchronize` event for c9399b52 never fired, and NOTHING ran on that head sha --
// including .github/workflows/legacy-authorization-surface-gate.yml, whose `paths:` filter names
// firestore.rules and was entirely correct. a2f4e457 merged the PR and the recorded legacy
// authorization corpus drifted 43 -> 37 call sites with no gate having observed it.
//
// The bypass is therefore not a path filter defect. It is that a workflow may author a commit
// that no workflow can ever see. The only point at which that is visible from inside the
// repository is the PR that introduces the workflow file itself -- which IS human-pushed, and
// which this fence runs on.
//
// ============================ WHAT IS FENCED, AND WHAT IS NOT ============================
//
// Fenced: a workflow file under .github/workflows/ that runs `git push`. That is the one shape
// that produces repository content no PR gate can observe.
//
// NOT fenced: the three governed EOS intake workflows below. They are an Owner-sanctioned,
// approval-gated integration path and this fence does not weaken them. They are recorded here
// exactly so that a FOURTH one cannot arrive unnoticed.
//
// ============================ THE ALLOWLIST IS A RATCHET ============================
//
// ALLOWED_SELF_PUSH may only SHRINK. Adding a line is not a fix -- it is a new instance of the
// defect, and it has to be argued for on its own PR, where the `.github/workflows/**` change is
// plainly visible to a human reviewer. Deleting a line, once the workflow stops pushing or is
// retired, IS the fix.
//
// A stale entry is a violation for the same reason a stale baseline entry is: it would silently
// tolerate the pattern coming back under a name that is already blessed. So an allowlisted
// workflow that no longer exists, or that no longer pushes, fails this fence until its line is
// removed.
//
// Run: node scripts/workflowSelfPushFence.mjs
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const WORKFLOWS_DIR = join(ROOT, ".github", "workflows");

/**
 * Workflows that pushed repository content before this fence existed.
 *
 * SHRINK ONLY. See the header. Each of these is an Owner-sanctioned governed intake path; none of
 * them is a template for a new one.
 */
export const ALLOWED_SELF_PUSH = new Set([
  "eos-intake-writeback.yml",
  "eos-issue-intake.yml",
  "eos-patch-integrate.yml",
]);

/**
 * Does this workflow source run `git push`?
 *
 * Deliberately a source scan rather than a YAML walk: the push can be buried in a `run:` block in
 * bash or pwsh, behind a shell variable, or inside a retry loop, and every one of those is the
 * same defect. Comment lines are stripped first so that this file's own prose -- and the prose in
 * any workflow that DISCUSSES pushing -- cannot trip it.
 *
 * Returns the 1-based line numbers of the matches, empty when the workflow does not push.
 */
export function findSelfPushLines(source) {
  const hits = [];
  const lines = String(source).split(/\r?\n/);
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (/^\s*#/.test(line)) continue; // whole-line YAML comment: prose, not a step
    if (/(^|[\s;&|`("'])git\s+push\b/.test(line)) hits.push(i + 1);
  }
  return hits;
}

export function listWorkflowFiles(dir = WORKFLOWS_DIR) {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"))
    .sort();
}

/**
 * The whole fence, as data. Returns { violations, stale } -- both empty means the tree is clean.
 */
export function auditWorkflows({
  dir = WORKFLOWS_DIR,
  allowed = ALLOWED_SELF_PUSH,
  files = null,
  readFile = (f) => readFileSync(join(dir, f), "utf8"),
} = {}) {
  const names = files ?? listWorkflowFiles(dir);
  const pushing = new Map();
  for (const name of names) {
    const lines = findSelfPushLines(readFile(name));
    if (lines.length) pushing.set(name, lines);
  }

  const violations = [...pushing]
    .filter(([name]) => !allowed.has(name))
    .map(([name, lines]) => ({ name, lines }));

  const present = new Set(names);
  const stale = [...allowed]
    .filter((name) => !pushing.has(name))
    .map((name) => ({
      name,
      reason: present.has(name) ? "no longer pushes repository content" : "workflow no longer exists",
    }));

  return { violations, stale };
}

function main() {
  const { violations, stale } = auditWorkflows();
  const problems = [];

  for (const v of violations) {
    problems.push(
      `.github/workflows/${v.name} pushes repository content (line${v.lines.length > 1 ? "s" : ""} ` +
        `${v.lines.join(", ")}). A workflow-authored push does not trigger workflows, so the commit ` +
        `it creates can never be gated. Do this change through a pull request instead.`,
    );
  }
  for (const s of stale) {
    problems.push(
      `ALLOWED_SELF_PUSH lists ${s.name}, but it ${s.reason}. Remove the line from ` +
        `scripts/workflowSelfPushFence.mjs -- the allowlist may only shrink.`,
    );
  }

  if (problems.length) {
    console.error("Workflow self-push fence FAILED:");
    for (const p of problems) console.error(`  - ${p}`);
    process.exitCode = 1;
    return;
  }
  console.log(
    `Workflow self-push fence OK: ${listWorkflowFiles().length} workflows scanned, ` +
      `${ALLOWED_SELF_PUSH.size} allowlisted self-pushing workflows, 0 new ones.`,
  );
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) main();
